language: python

python:
- 3.6
- 3.7
- 3.8

install:
- pip install poetry
- poetry install

script:
- poetry run flake8
- poetry run isort -c -df
- poetry run pytest --cov=ptera --cov-report term-missing
- poetry run coverage report | tail -1 | egrep "TOTAL +[0-9]+ +0 +100%"
